// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckUsernameExists(ctx context.Context, username pgtype.Text) (bool, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteUserProfile(ctx context.Context, id pgtype.UUID) error
	GetNote(ctx context.Context, id pgtype.UUID) (GetNoteRow, error)
	GetNoteForFlashcard(ctx context.Context, arg GetNoteForFlashcardParams) (GetNoteForFlashcardRow, error)
	GetUserNotes(ctx context.Context, arg GetUserNotesParams) ([]GetUserNotesRow, error)
	GetUserProfile(ctx context.Context, id pgtype.UUID) (UserProfile, error)
	GetUserProfileByUsername(ctx context.Context, username pgtype.Text) (UserProfile, error)
	ListUserProfiles(ctx context.Context, arg ListUserProfilesParams) ([]UserProfile, error)
	SearchNotesBySimilarity(ctx context.Context, arg SearchNotesBySimilarityParams) ([]SearchNotesBySimilarityRow, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (UpdateNoteRow, error)
	//  COALESCE is used to update the user profile with the new values if they are not null, if they are null, the old value will be kept.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
